apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/part-of: hermes
data:
  CF_ACCOUNT_ID: {{ .Values.cloudflare.accountId | quote }}
  CF_TUNNEL_ID: {{ .Values.cloudflare.tunnelId | quote }}
  DOMAIN: {{ .Values.cloudflare.domain | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/part-of: hermes
data:
  {{- range $key, $value := .Values.hermes.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-toolsets-override
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/part-of: hermes
data: {}
