{{- if .Values.cloudflare.ingress.enabled }}
{{- $instance := include "hermes.instance" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $instance }}-ingress
  namespace: {{ include "hermes.ns" . }}
  labels:
    app.kubernetes.io/part-of: hermes
  annotations:
    kubernetes.io/ingress.class: {{ .Values.cloudflare.ingress.className }}
spec:
  rules:
    - host: {{ include "hermes.subst" (list $ .Values.cloudflare.domain) }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $instance }}-agent-svc
                port:
                  number: {{ .Values.hermes.service.gatewayPort }}
{{- end }}
